### ISSUE TITLE
Print : naming conflict

### ISSUE THREAD

**Issue by raphaelbastide** [aptgetETH/WaveShare-ePaper-Display#2]
There is a naming conflict for `print` [here](https://github.com/aptgetETH/WaveShare-ePaper-Display/blob/master/WaveshareDisplay.py#L57) 

    File "WaveShare-ePaper-Display/WaveshareDisplay.py", line 57
        def print(self,x,y,text):

Renaming the function solves the issue in my case.

**Comment by jonjreeves** [comment]
I renamed the method and pushed it. Print worked on my setup but it is good style to not reuse any of the python function names.
